### ISSUE TITLE
Handling of Ids having optional elements

### ISSUE THREAD

**Issue by ahzf** [hubject/opcp#11]
The document https://github.com/hubject/opcp/blob/main/OPCP-1.0.0/docs/05_handling-of-ids.md describes the handling of Ids in the e-mobility space. Ids can have optional elements like `-` or `*`, but it is not specified how to compare two identifiers for equality, when they have different optional elements. E.g. is "DE*GEF" the same as "DEGEF"? I would say yes.

All this has an implication on the implementation of ids, as it would be better not to implement them just as a string, but as a complex data structure having special comparison methods.

**Comment by steffenrhinow** [comment]
HI Achim,
The ISO is defining that DE-GEF... and DEGEF are ok for an EMAID. But its also defining that 15characters are the maximum for the authorization message. So here the ISO is not consistent. 
This is why we decided, that our system can handle both versions, but we are normalising the strings and remove the "-". 
This is working since a while and error proof until now.

**Comment by ahzf** [comment]
Well, I can not test your OPCP implementation, but within the normal Hubject OICP portal I get different results and this is not how I would understand "optional characters".

![image](https://user-images.githubusercontent.com/285458/189529894-042dd5ff-7aed-4735-8541-b390506bf08a.png)

**Comment by steffenrhinow** [comment]
Hi Achim,
thats correct - the two systems are not connected to each other. We decided to do not tie PnC to Roaming HBS. 
But if a normalized emaid is getting authorized at HBS - it will also match to the "non normalized" string.
If you want to try out PnC as CPO/MO just contact us, we can give you access.
See ya
Steffen
